version: "3.8"
services:
  pythonapi:
    container_name: pythonapi
    build: .
    restart: always
    ports:
      - ${PORT_MAP}:${PORT}
    volumes:
      - .:/pythonapi
    env_file:
      - .env